In [ ]:
! explorer .

In [ ]:
! code .

## create geometory
using https://github.com/sintefmath/Splipy

### create pandas data

### create curve(2d surface →　path)
using trimesh,shapely

### create 3d surface
using Splipy

## modify

## stl 
using trimesh,shapely

- https://trimsh.org/examples/section.html

In [ ]:
import trimesh
import numpy as np
from shapely.geometry import LineString
%pylab inline

In [ ]:
# load the mesh from filename
# file objects are also supported
mesh = trimesh.load_mesh('test_file/test.stl')

In [ ]:
mesh

In [ ]:
mesh.show()

In [ ]:
# get a single cross section of the mesh
slice = mesh.section(plane_origin=mesh.centroid, 
                     plane_normal=[1,0,0])

In [ ]:
for i in range(30):
    x= i-3.69
    print(x)
    slice = mesh.section(plane_origin=[i-3.69,0,0], 
                         plane_normal=[1,0,0])
    # we can move the 3D curve to a Path2D object easily
    slice_2D, to_3D = slice.to_planar()
    slice_2D.show()

In [ ]:
# the section will be in the original mesh frame
slice.show()

In [ ]:
# we can move the 3D curve to a Path2D object easily
slice_2D, to_3D = slice.to_planar()
slice_2D.show()

In [ ]:
aaa=  slice_2D.to_dict()

In [ ]:
aaa

In [ ]:
# if we wanted to take a bunch of parallel slices, like for a 3D printer
# we can do that easily with the section_multiplane method
# we're going to slice the mesh into evenly spaced chunks along z
# this takes the (2,3) bounding box and slices it into [minz, maxz]
z_extents = mesh.bounds[:,2]
# slice every .125 model units (eg, inches)
z_levels  = np.arange(*z_extents, step=.125)

In [ ]:
# find a bunch of parallel cross sections
sections = mesh.section_multiplane(plane_origin=mesh.bounds[0], 
                                   plane_normal=[0,0,1], 
                                   heights=z_levels)
sections

In [ ]:
# summing the array of Path2D objects will put all of the curves
# into one Path2D object, which we can plot easily
combined = np.sum(sections[6:])
combined.show()

In [ ]:
# if we want to intersect a line with this 2D polygon, we can use shapely methods
polygon = slice_2D.polygons_full[0]
# intersect line with one of the polygons
hits = polygon.intersection(LineString([[-4,-1], [3,0]]))
# check what class the intersection returned
hits.__class__

In [ ]:
hits

In [ ]:
plt.plot(*hits.xy, color='r')

In [ ]:
slice_2D.show()

In [ ]:
# the medial axis is available for closed Path2D objects
(slice_2D + slice_2D.medial_axis()).show()

In [ ]:
from stl import mesh
from mpl_toolkits import mplot3d
from matplotlib import pyplot

# Create a new plot
figure = pyplot.figure()
axes = mplot3d.Axes3D(figure)

# Load the STL files and add the vectors to the plot
# your_mesh = mesh.Mesh.from_file('tests/stl_binary/HalfDonut.stl')
your_mesh = mesh.Mesh.from_file('test_file/test.stl')
axes.add_collection3d(mplot3d.art3d.Poly3DCollection(your_mesh.vectors))

# Auto scale to the mesh size
scale = your_mesh.points.flatten(-1)
axes.auto_scale_xyz(scale, scale, scale)

# Show the plot to the screen
pyplot.show()

In [ ]:
axes.

## factory

In [3]:
from splipy import *
from numpy import pi,cos,sin,transpose,array,sqrt
from splipy.io import STL
from splipy import surface_factory

# define a parametric representation of the trefoil knot (to be sampled)
def trefoil(u):
    x = [41*cos(u) - 18*sin(  u) -  83*cos(2*u) - 83*sin(2*u) - 11*cos(3*u) + 27*sin(3*u),
       36*cos(u) + 27*sin(  u) - 113*cos(2*u) + 30*sin(2*u) + 11*cos(3*u) - 27*sin(3*u),
       45*sin(u) - 30*cos(2*u) + 113*sin(2*u) - 11*cos(3*u) + 27*sin(3*u)]
    return transpose(array(x))

knot_curve   = curve_factory.fit(trefoil, 0, 2*pi) # adaptive curve fit of trefoil knot
square_curve = 15 * curve_factory.n_gon(4)         # square cross-section


In [4]:
my_surface   = surface_factory.sweep(knot_curve, square_curve)  # sweep out the surface

In [5]:
# STL files are tessellated linear triangles. View with i.e. meshlab
with STL('torus_.stl') as my_file:
    my_file.write(my_surface, n=(50, 150)) # specify resolution of 50x150 evaluation pt

In [ ]:
square_curve

In [ ]:
! explorer .

In [1]:
from splipy.io import STL
from splipy import surface_factory

# create a NURBS torus
my_torus = surface_factory.torus(minor_r=1, major_r=4)

# STL files are tessellated linear triangles. View with i.e. meshlab
with STL('torus.stl') as my_file:
    my_file.write(my_torus, n=(50, 150)) # specify resolution of 50x150 evaluation pt

In [2]:
my_torus

p=3, [-1.57079633  0.          0.          1.57079633  1.57079633  3.14159265
  3.14159265  4.71238898  4.71238898  6.28318531  6.28318531  7.85398163], C0-periodic
p=3, [-1.57079633  0.          0.          1.57079633  1.57079633  3.14159265
  3.14159265  4.71238898  4.71238898  6.28318531  6.28318531  7.85398163], C0-periodic
[5. 0. 0. 1.]
[3.53553391 0.         0.70710678 0.70710678]
[4. 0. 1. 1.]
[2.12132034 0.         0.70710678 0.70710678]
[3. 0. 0. 1.]
[ 2.12132034  0.         -0.70710678  0.70710678]
[ 4.  0. -1.  1.]
[ 3.53553391  0.         -0.70710678  0.70710678]
[3.53553391 3.53553391 0.         0.70710678]
[2.5 2.5 0.5 0.5]
[2.82842712 2.82842712 0.70710678 0.70710678]
[1.5 1.5 0.5 0.5]
[2.12132034 2.12132034 0.         0.70710678]
[ 1.5  1.5 -0.5  0.5]
[ 2.82842712  2.82842712 -0.70710678  0.70710678]
[ 2.5  2.5 -0.5  0.5]
[-8.8817842e-16  5.0000000e+00  0.0000000e+00  1.0000000e+00]
[-4.44089210e-16  3.53553391e+00  7.07106781e-01  7.07106781e-01]
[-8.8817842e-16  4.000